name: Run NeoBux-game_01 Script

on:
  workflow_dispatch:  # Manually trigger from GitHub Actions
  schedule:
    - cron: "0 */7 * * *"  # Runs once every 7 hours

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Playwright
        run: npm install playwright && npx playwright install firefox

      - name: Run automation script 100 times
        run: |
          for i in {1..100}; do
            echo "Running iteration $i"
            node neobux_01.js  # Replace with your actual script filename
          done
        env:
          DISPLAY: ':99.0'  # Enable Xvfb to run headless
