name: Run NeoBux-2 Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"  # Runs every 5 hours

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Playwright and Firefox
        run: |
          npm install playwright
          npx playwright install firefox

      - name: Display current IP address
        run: |
          echo "Current IP address of this runner:"
          curl -s icanhazip.com
          echo ""

      - name: Run automation script
        run: node x7k9p23-survey.js
        env:
          DISPLAY: ':99.0'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push updated session
        run: |
          git add x7k9p23.json
          git commit -m "Update session file automatically [skip ci]" || echo "No changes to commit"
          git push origin main
