name: Run build-tester Script

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 */2 * * *' # Runs every 1 hours

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'

      - name: Install Playwright
        run: npm install playwright && npx playwright install chromium

      - name: Install Xvfb (GUI Emulator)
        run: sudo apt update && sudo apt install -y xvfb

      - name: Clear old Nodeman profile
        run: rm -rf /home/runner/Nodeman/builKms34km

      - name: Clear old extKms34km files
        run: rm -rf /home/runner/Nodeman/extKms34km

      - name: Extract Chromium Profile
        run: |
          mkdir -p /home/runner/Nodeman/
          tar -xzvf builKms34km.tar.gz -C /home/runner/Nodeman/

      - name: Extract Extension
        run: |
          mkdir -p /home/runner/Nodeman/
          tar -xzvf extKms34km.tar.gz -C /home/runner/Nodeman/

      - name: Start Xvfb (Simulate GUI)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Run builKms34km script
        run: node noKms34km.js
        env:
          DISPLAY: ':99.0'  # Use Xvfb display for GUI support
