name: Run NeoBux-game_01 Script

on:
  workflow_dispatch:
    inputs:
      start_iteration:
        description: 'Starting iteration number'
        default: '1'
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: neobux-script-run
  cancel-in-progress: true

jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Playwright
        run: npm install playwright && npx playwright install firefox

      - name: Run automation script with timeout
        run: |
          START_ITERATION=${{ github.event.inputs.start_iteration || 1 }}
          END_ITERATION=100
          TIMEOUT_SECONDS=$((5 * 3600 + 50 * 60))  # 5 hours 50 minutes
          START_TIME=$(date +%s)

          for ((i=$START_ITERATION; i<=$END_ITERATION; i++)); do
            CURRENT_TIME=$(date +%s)
            ELAPSED_SECONDS=$((CURRENT_TIME - START_TIME))

            if [ $ELAPSED_SECONDS -ge $TIMEOUT_SECONDS ]; then
              echo "Approaching 5h50m limit after iteration $((i-1)). Triggering restart..."
              curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/actions/workflows/$(basename ${{ github.workflow }}) \
                -d "{\"ref\":\"${{ github.ref }}\",\"inputs\":{\"start_iteration\":\"$i\"}}"
              exit 0
            fi

            echo "Running iteration $i"
            node neox7k9p2m_01.js  # Updated filename here
          done

          echo "Completed all iterations up to $END_ITERATION"
        env:
          DISPLAY: ':99.0'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
