name: Run NeoBux-game Script

on:
  workflow_dispatch:  # Manually trigger from GitHub Actions
  schedule:
    - cron: "0 */8 * * *"  # Runs every 8 hours

concurrency:
  group: neobux-game
  cancel-in-progress: true

jobs:
  automate:
    runs-on: ubuntu-latest
    timeout-minutes: 330  # Auto-terminate after 5 hours 30 minutes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'

      - name: Install system dependencies
        run: |
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2 libpango-1.0-0 libxss1

      - name: Install Playwright and Firefox
        run: |
          npm install playwright
          npx playwright install firefox --with-deps

      - name: Start Xvfb
        run: |
          sudo Xvfb :99 -screen 0 1280x720x24 &

      - name: Run automation script 100 times
        run: |
          for i in {1..100}; do
            echo "Running iteration $i"
            node neox7k9p2m.js  # Replace with your actual script filename
          done
        env:
          DISPLAY: ':99'  # Use the virtual display for headless Firefox

      - name: Verify Node.js version (optional)
        run: node -v
